Name: Product
Host: 0.0.0.0
Port: 8001

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true&loc=Local

CacheRedis:
- Host: 127.0.0.1:6379
  Type: node # node 可以不写，可以设为cluster
  # Pass:

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
    - 127.0.0.1:2379
    Key: product.rpc